baseURL = 'https://zealove.github.io/'
# languageCode = 'en-us'
title = "ZeaLoVe's Blogs"
theme = "ananke" 
publishDir = "./public"
DefaultContentLanguage = "cn"

[languages]
  [languages.cn]
    title = "ZeaLoVe's Blogs"
    weight = 1
    contentDir = "content/cn"
  [languages.en]
    title = "ZeaLoVe's Blogs"
    weight = 2
    contentDir = "content/en"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  featured_image = "/images/tasada.jpg"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/ZeaLoVe16"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/ZeaLoVe"

